#include "../minunit.h"


/**
 * Function: Send_command_and_write_to_file
 * -----------------
 * This function is used to pass a command to the minishell and write the output
 * to a file. The first argument is the command to be passed, and the second
 * argument is the name of the file to be written.
 * 
 * To process the command, the function popen is used. It opens a process by
 * creating a pipe, forking, dupping the pipe into stdin/stdout, and executing
 * the given command. The function returns a pointer to the file.
 *  
 * @param: command: The command to be passed to the minishell.
 * @param: filename: The name of the file to be written.
 * 
 * @var: fp: The pointer to the file.
 * @var: outfile: The pointer to the file.
 * @var: buffer: The buffer to store the output of the command.
 * 
 * @return: Returns a pointer to the file.
 *
 */

FILE *send_command_and_write_to_file(char *command, char *filename)
{
    FILE *fp;
    FILE *outfile;

    char buffer[1024];

    fp = popen(command, "r");
    if (fp == NULL)
    {
        printf("Failed to run command\n");
        exit(1);
    }

    outfile = fopen(filename, "w");
    if (outfile == NULL)
    {
        printf("Failed to open file\n");
        exit(1);
    }
    
    while (fgets(buffer, sizeof(buffer), fp) != NULL)
        fputs(buffer, outfile);
    pclose(fp);
    fclose(outfile);
    return (outfile);
}

/**
 * Function: Read_line
 * -----------------
 * This function is used to read a line from a file and return it as a string.
 * 
 * @param: filename: The name of the file to be read.
 * 
 * @var: file: The pointer to the file.
 * 
 * @return: Returns a pointer to the string.
 *
 */

char *read_line(char *filename)
{
    FILE *file = fopen(filename, "r");
    if (file == NULL)
    {
        printf("Failed to open file\n");
        exit(1);
    }
    char *content = malloc(sizeof(char) * 1024);
    fgets(content, 1024, file);
    fclose(file);
    return (content);
}

/**
 * Function: Compare_files
 * -----------------
 * This function is used compare two strings generated by the function
 * read_line. If the strings are not equal, the function will print the
 * line where the strings are different and exit the program. If the strings
 * are equal, the function will print that the files are equal.
 * 
 * Thus, we will be able to check if the output of the minishell is equal to
 * the output of the bash.
 * 
 * @param: filename1: The name of the first file to be read.
 * @param: filename2: The name of the second file to be read.
 * 
 * @var: file1: Pointer to the first file, used to read the first file.
 * @var: file2: Pointer to the second file, used to read the second file.
 * @var: line1: Pointer to the string of the first file, used to store the
 *             string of the first file.
 * @var: line2: Pointer to the string of the second file, used to store the
 *            string of the second file.
 * @var: number_line: The number of the line where the strings are different.
 * @var: is_equal: Boolean variable used to check if the strings are equal.
 * 
 * @return: Returns nothing.
 *
 */

void compare_files(char *filename1, char *filename2)
{
    FILE *file1 = fopen(filename1, "r");
    FILE *file2 = fopen(filename2, "r");
    char line1[10000];
    char line2[10000];
    int number_line = 1;
    t_bool is_equal = true;

    if (file1 == NULL || file2 == NULL)
    {
        printf(RED"Failed to open file\n"RESET);
        exit(1);
    }
    while (fgets(line1, 10000, file1) != NULL && fgets(line2, 10000, file2) != NULL)
    {
        if (strcmp(line1, line2) != 0)
        {
            is_equal = false;
            printf(RED"Files are not equal at line %d\n" RESET, number_line);
            printf("File 1: %s", line1);
            printf("File 2: %s\n", line2);
            exit(1);
        }
        number_line++;
    }
    if (is_equal == true)
        printf(GREEN"Files are equal\n" RESET);

}

/**
 * Function: Test_...
 * -----------------
 * This function is used by the minunit library to run a test. It is used to
 * test the command or some part of the code.
 * 
 * @param: void: The function does not receive any arguments.
 * @function: system: The system function is used to run a command in the shell.
 * 
 * @return: Returns nothing.
 *
 */

MU_TEST(echo_1arg_to_file)
{
	pid_t pid;

    pid = fork();
	system("echo fucker > echo_bash.txt");

    if (pid == 0)
        execlp("/nfs/homes/brunrodr/09.MINISHELL/42SP_08_minishell/minishell", "minishell", NULL);
    else if (pid > 0)
    {
        sleep(1);
        kill(pid, SIGINT);
    }

    send_command_and_write_to_file("echo fucker", "echo_minishell.txt");
    compare_files("echo_minishell.txt", "echo_bash.txt");
}

//############################### 2nd test ###############################

MU_TEST(echo_2arg_to_file)
{
	pid_t pid;

    pid = fork();
	system("echo sucker dicker > ./txt/echo_bash2.txt");

    if (pid == 0)
        execlp("/nfs/homes/brunrodr/09.MINISHELL/42SP_08_minishell/minishell", "minishell", NULL);
    else if (pid > 0)
    {
        sleep(1);
        kill(pid, SIGINT);
    }

    send_command_and_write_to_file("echo sucker dicker", "./txt/echo_minishell2.txt");
    compare_files("./txt/echo_minishell2.txt", "./txt/echo_bash2.txt");
}

//############################### 3rd test ###############################

MU_TEST(echo_expand_variable)
{
	pid_t pid;

    pid = fork();
	system("echo $USER > ./txt/echo_bash3.txt");

    if (pid == 0)
        execlp("/nfs/homes/brunrodr/09.MINISHELL/42SP_08_minishell/minishell", "minishell", NULL);
    else if (pid > 0)
    {
        sleep(1);
        kill(pid, SIGINT);
    }

    send_command_and_write_to_file("echo $USER", "./txt/echo_minishell3.txt");
    compare_files("./txt/echo_minishell3.txt", "./txt/echo_bash3.txt");
}

//############################### 4th test ###############################

MU_TEST(echo_expand_variable_between_single_quotes)
{
	pid_t pid;

    pid = fork();
	system("echo '$USER' > ./txt/echo_bash4.txt");

    if (pid == 0)
        execlp("/nfs/homes/brunrodr/09.MINISHELL/42SP_08_minishell/minishell", "minishell", NULL);
    else if (pid > 0)
    {
        sleep(1);
        kill(pid, SIGINT);
    }

    send_command_and_write_to_file("echo '$USER'", "./txt/echo_minishell4.txt");
    compare_files("./txt/echo_minishell4.txt", "./txt/echo_bash4.txt");
}

//############################### 5th test ###############################

MU_TEST(echo_expand_variable_between_double_quotes)
{
	pid_t pid;

    pid = fork();
	system("echo \"$USER\" > ./txt/echo_bash5.txt");

    if (pid == 0)
        execlp("/nfs/homes/brunrodr/09.MINISHELL/42SP_08_minishell/minishell", "minishell", NULL);
    else if (pid > 0)
    {
        sleep(1);
        kill(pid, SIGINT);
    }

    send_command_and_write_to_file("echo \"$USER\"", "./txt/echo_minishell5.txt");
    compare_files("./txt/echo_minishell5.txt", "./txt/echo_bash5.txt");
}

//############################### 6th test ###############################

MU_TEST(echo_expand_variable_between_double_quotes_and_single_quotes)
{
	pid_t pid;

    pid = fork();
	system("echo \"'$USER'\" > ./txt/echo_bash6.txt");

    if (pid == 0)
        execlp("/nfs/homes/brunrodr/09.MINISHELL/42SP_08_minishell/minishell", "minishell", NULL);
    else if (pid > 0)
    {
        sleep(1);
        kill(pid, SIGINT);
    }

    send_command_and_write_to_file("echo \"'$USER'\"", "./txt/echo_minishell6.txt");
    compare_files("./txt/echo_minishell6.txt", "./txt/echo_bash6.txt");
}


//############################### 7th test ###############################

MU_TEST(echo_expand_variable_between_single_quotes_double_quotes)
{
	pid_t pid;

    pid = fork();
	system("echo '\"$USER\"' > ./txt/echo_bash7.txt");

    if (pid == 0)
        execlp("/nfs/homes/brunrodr/09.MINISHELL/42SP_08_minishell/minishell", "minishell", NULL);
    else if (pid > 0)
    {
        sleep(1);
        kill(pid, SIGINT);
    }

    send_command_and_write_to_file("echo '\"$USER\"'", "./txt/echo_minishell7.txt");
    compare_files("./txt/echo_minishell7.txt", "./txt/echo_bash7.txt");
}


//############################### 8th test ###############################

MU_TEST(echo_expand_double_quotes)
{
	pid_t pid;

    pid = fork();
	system("echo \"'\" \"'\" \"'\" > ./txt/echo_bash8.txt");

    if (pid == 0)
        execlp("/nfs/homes/brunrodr/09.MINISHELL/42SP_08_minishell/minishell", "minishell", NULL);
    
    compare_files("./txt/echo_minishell8.txt", "./txt/echo_bash8.txt");
}

//############################### 9th test ###############################

MU_TEST(echo_expand_single_quotes)
{
	pid_t pid;

    pid = fork();
	system("echo '\"' '\"' '\"' > ./txt/echo_bash9.txt");

    if (pid == 0)
        execlp("/nfs/homes/brunrodr/09.MINISHELL/42SP_09_minishell/minishell", "minishell", NULL);
    else if (pid > 0)
    {
        sleep(3);
        send_command_and_write_to_file("echo '\"' '\"' '\"'", "./txt/echo_minishell9.txt");
        kill(pid, SIGINT);
    }
    compare_files("./txt/echo_minishell9.txt", "./txt/echo_bash9.txt");
}

//############################### 10th test ###############################

MU_TEST(echo_expand_single_quotes_and_double_quotes)
{
	pid_t pid;

    pid = fork();
	system("echo '\"otario' '\"$USER' '\"' > ./txt/echo_bash10.txt");

    if (pid == 0)
        execlp("/nfs/homes/brunrodr/09.MINISHELL/42SP_09_minishell/minishell", "minishell", NULL);
    else if (pid > 0)
    {
        sleep(1);
        kill(pid, SIGINT);
    }

    send_command_and_write_to_file("echo '\"otario' '\"$USER' '\"'", "./txt/echo_minishell10.txt");
    compare_files("./txt/echo_minishell10.txt", "./txt/echo_bash10.txt");
}

//############################### 11th test ###############################

MU_TEST(echo_expand_double_quotes_and_single_quotes)
{
	pid_t pid;

    pid = fork();
	system("echo \"'otario\" \"'$USER\" '\"' > ./txt/echo_bash11.txt");

    if (pid == 0)
        execlp("/nfs/homes/brunrodr/09.MINISHELL/42SP_09_minishell/minishell", "minishell", NULL);
    else if (pid > 0)
    {
        sleep(1);
        kill(pid, SIGINT);
    }

    send_command_and_write_to_file("echo \"'otario\" \"'$USER\" '\"'", "./txt/echo_minishell11.txt");
    compare_files("./txt/echo_minishell11.txt", "./txt/echo_bash11.txt");
}

//############################### 12th test ###############################

MU_TEST(echo_scape_double_quotes)
{
	pid_t pid;

    pid = fork();
	system("echo \\\"'$USER\" > ./txt/echo_bash12.txt");

    if (pid == 0)
        execlp("/nfs/homes/brunrodr/09.MINISHELL/42SP_09_minishell/minishell", "minishell", NULL);
    else if (pid > 0)
    {
        sleep(1);
        kill(pid, SIGINT);
    }

    send_command_and_write_to_file("echo \\\"'$USER\"", "./txt/echo_minishell12.txt");
    compare_files("./txt/echo_minishell12.txt", "./txt/echo_bash12.txt");
}

//############################### 13th test ###############################

MU_TEST(echo_scape_single_quotes)
{
	pid_t pid;

    pid = fork();
	system("echo \\'\"$USER\"' > ./txt/echo_bash12.txt");

    if (pid == 0)
        execlp("/nfs/homes/brunrodr/09.MINISHELL/42SP_09_minishell/minishell", "minishell", NULL);
    else if (pid > 0)
    {
        sleep(1);
        kill(pid, SIGINT);
    }

    send_command_and_write_to_file("echo \\'\"$USER\"'", "./txt/echo_minishell12.txt");
    compare_files("./txt/echo_minishell12.txt", "./txt/echo_bash12.txt");
}

MU_TEST_SUITE(test_suite)
{
    printf(YELLOW "Initializing minunit tests\n" RESET);

    printf("\n------------------- TEST ECHO n°1 -------------------\n");
    MU_RUN_TEST(echo_1arg_to_file);

    printf("\n------------------- TEST ECHO n°2 -------------------\n");
    MU_RUN_TEST(echo_2arg_to_file);

    printf("\n------------------- TEST ECHO n°3 -------------------\n");
    MU_RUN_TEST(echo_expand_variable);

    printf("\n------------------- TEST ECHO n°4 -------------------\n");
    MU_RUN_TEST(echo_expand_variable_between_single_quotes);

    printf("\n------------------- TEST ECHO n°5 -------------------\n");
    MU_RUN_TEST(echo_expand_variable_between_double_quotes);

    printf("\n------------------- TEST ECHO n°6 -------------------\n");
    MU_RUN_TEST(echo_expand_variable_between_double_quotes_and_single_quotes);

    printf("\n------------------- TEST ECHO n°7 -------------------\n");
    MU_RUN_TEST(echo_expand_variable_between_single_quotes_double_quotes);

    printf("\n------------------- TEST ECHO n°8 -------------------\n");
    MU_RUN_TEST(echo_expand_double_quotes);

    printf("\n------------------- TEST ECHO n°9 -------------------\n");
    MU_RUN_TEST(echo_expand_single_quotes);

    printf("\n------------------- TEST ECHO n°10 -------------------\n");
    MU_RUN_TEST(echo_expand_single_quotes_and_double_quotes);

    printf("\n------------------- TEST ECHO n°11 -------------------\n");
    MU_RUN_TEST(echo_expand_double_quotes_and_single_quotes);

    printf("\n------------------- TEST ECHO n°12 -------------------\n");
    MU_RUN_TEST(echo_scape_double_quotes);

    printf("\n------------------- TEST ECHO n°13 -------------------\n");
    MU_RUN_TEST(echo_scape_single_quotes);
}


int main(void)
{
    MU_RUN_SUITE(test_suite);
    return (0);
}