/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   node_creation.c                                    :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: allesson <allesson@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/11/15 21:32:41 by aperis-p          #+#    #+#             */
/*   Updated: 2023/12/12 19:28:29 by allesson         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "../include/minishell.h"

/**
 * Function: new_cmd_file_node
 * -----------------
 * This function creates a new node in the command list,
 * appends to args, if a token that has type IDENTIFIER and
 * if there is a TYPE_COMMAND node at cmd_list aleady,
 * also verifys if the previous node is a redirect node
 * in order to create the right type of node in the command list.
 * 
 * @param: **current: The current token.
 * 
 * @return: void.
 * 
*/

void new_cmd_file_node(t_tkn_list **current)
{
	if(tkn_list_size((*current)->prev) && is_redirect((*current)->prev->type))
	{
		add_cmd_list((t_cmd_list){
			.type = TYPE_FILE,
			.args = (*current)->content,
			.weight = DEFAULT,
			});
		*current = (*current)->next;
		return ;
	}
	else if(find_command(g_global.cmd_list))
	{
		append_expand(current);
			if(!(*current))
				return ;
	}
	else
	{			
		add_cmd_list((t_cmd_list){
			.type = TYPE_COMMAND,
			.args = (*current)->content,
			.weight = DEFAULT,
		});
		*current = (*current)->next;
	}
}

/**
 * Function: new_redirect_node
 * -----------------
 * This function creates a new type REDIRECT node
 * in the command list for those nodes coming from
 * the tkn_list with type INFILE, REDIRECT, HERE_DOC
 * and APPEND.
 * 
 * @param: **current: The token list generated by the tokenizer.
 * @var: has_here_doc: A boolean that is true if the current token is of type HERE_DOC.
 * 
 * @return: void.
 * 
*/

void	new_redirect_node(t_tkn_list **current)
{
	t_bool has_here_doc;
	t_op weight;

	has_here_doc = false;
	weight = OP_REDIRECT;		
	if((*current)->type == HERE_DOC)
	{
		has_here_doc = true;
		weight = OP_HEREDOC;
	}
	else
		has_here_doc = false;
	add_cmd_list((t_cmd_list){
		.type = TYPE_REDIRECT,
		.args = tkn_type_converter((*current)->type),
		.weight = weight,
		.here_doc = has_here_doc,
	});
	*current = (*current)->next;
}

/**
 * Function: new_subshell_node
 * -----------------
 * This function creates a new type OPERATOR node
 * in the command list for those nodes coming from
 * the tkn_list, which are between O_PARENTESIS and C_PARENTESIS.
 * 
 * @param: **current: The token list generated by the tokenizer.
 * 
 * @return: void.
 * 
*/

void	new_subshell_node(t_tkn_list **current)
{
	add_cmd_list((t_cmd_list){
		.type = TYPE_SUBSHELL,
		.args = tkn_type_converter((*current)->type),
		.weight = DEFAULT,
	});
	*current = (*current)->next;
	while((*current)->type != C_PARENTESIS)
	{
		g_global.cmd_list = last_cmd_list(g_global.cmd_list);
		g_global.cmd_list->args = gnl_strjoin(g_global.cmd_list->args, (*current)->content);
		if((*current)->next->type != C_PARENTESIS)
			g_global.cmd_list->args = gnl_strjoin(g_global.cmd_list->args, " ");
		*current = (*current)->next;
	}
	g_global.cmd_list->args = gnl_strjoin(g_global.cmd_list->args, tkn_type_converter((*current)->type));
	*current = (*current)->next;
}

/**
 * Function: new_operator_node
 * -----------------
 * This function creates a new type OPERATOR node
 * in the command list for those nodes coming from
 * the tkn_list as AND, OR and PIPE.
 * 
 * @param: **current: The token list generated by the tokenizer.
 * @var: weight: The precedence weight of the operator.
 * 
 * @return: void.
 * 
*/

void	new_operator_node(t_tkn_list **current)
{
	t_op weight;
	t_type type_operator;
	
	if ((*current)->type == PIPE)
	{
		type_operator = TYPE_PIPE;
		weight = OP_PIPE;
	}
	else
	{
		type_operator = TYPE_LOGICAL;
		weight = OP_LOGICAL;
	}
	add_cmd_list((t_cmd_list){
		.type = type_operator,
		.args = tkn_type_converter((*current)->type),
		.weight = weight,
	});
	*current = (*current)->next;
}
